spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/app10_prod?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: jaesoonlocal
    password: Local123$
  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    com.ll.exam.app10.app: info
custom:
  genFileDirPath: /gen